name: destinygetaways
favicon: null
layout_spectrum: 0.9855368791613728
typography_spectrum: 0.33982284273952246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10372868389822543
  lightness: 0.0567250931635499
  saturation: 0.6345831654034555
  rhythmicContrast: 0.5384234867524356
purpose: []
